version: '3.8'

services:
  gateway:
    image: ccadett/tutor-ui-web:${GATEWAY_VERSION-latest}
    networks:
      - public
      - application
    ports:
      - "${GATEWAY_PUBLISHED_PORT-80}:80"
      - "${GATEWAY_PUBLISHED_SSL_PORT-443}:443"
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
      - source: api_gateway.conf
        target: /etc/nginx/api_gateway.conf
    volumes:
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
  certbot:
    image: certbot/certbot:v2.3.0
    environment:
      HTTPS_PROXY: "http://proxy.uns.ac.rs:8080/"
      HTTP_PROXY: "http://proxy.uns.ac.rs:8080/"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure

configs:
  nginx.conf:
    name: nginx.conf-${nginx_conf_DIGEST}
    file: ./gateway/files/config/nginx.conf
  api_gateway.conf:
    name: api_gateway.conf-${api_gateway_conf_DIGEST}
    file: ./gateway/files/config/api_gateway.conf

networks:
  public:
    name: clean_cadet_public_${STAGE-dev}
    driver: overlay
    attachable: true
  application:
    name: clean_cadet_application_${STAGE-dev}
    driver: overlay
    external: true
