<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SKEXP0010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.68.0" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="Pgvector" Version="0.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tutor.BuildingBlocks.AI.Core\Tutor.BuildingBlocks.AI.Core.csproj" />
  </ItemGroup>

</Project>
