
services:
  pgadmin:
    image: dpage/pgadmin4:5.3
    networks:
      - operations
      - persistence
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ROOT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ROOT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 8081:80
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure

volumes:
  pgadmin:
    name: pgadmin_dev

networks:
  operations:
    name: operations_dev
    driver: overlay
    attachable: true
  persistence:
    name: clean_cadet_persistence_dev
    driver: overlay
    external: true
