CREATE TABLE "ArrangeTaskSubmissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ArrangeTaskId" integer NOT NULL,
    "LearnerId" integer NOT NULL,
    "IsCorrect" boolean NOT NULL,
    "TimeStamp" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ArrangeTaskSubmissions" PRIMARY KEY ("Id")
);


CREATE TABLE "AssessmentEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "KnowledgeComponentId" integer NOT NULL,
    CONSTRAINT "PK_AssessmentEvents" PRIMARY KEY ("Id")
);


CREATE TABLE "ChallengeHints" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Content" text NULL,
    CONSTRAINT "PK_ChallengeHints" PRIMARY KEY ("Id")
);


CREATE TABLE "ChallengeSubmissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SourceCode" text[] NULL,
    "ChallengeId" integer NOT NULL,
    "LearnerId" integer NOT NULL,
    "IsCorrect" boolean NOT NULL,
    "TimeStamp" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ChallengeSubmissions" PRIMARY KEY ("Id")
);


CREATE TABLE "InstructionalEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "KnowledgeComponentId" integer NOT NULL,
    CONSTRAINT "PK_InstructionalEvents" PRIMARY KEY ("Id")
);


CREATE TABLE "KCMastery" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Mastery" double precision NOT NULL,
    "KnowledgeComponentId" integer NOT NULL,
    "LearnerId" integer NOT NULL,
    CONSTRAINT "PK_KCMastery" PRIMARY KEY ("Id")
);


CREATE TABLE "Learners" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudentIndex" text NULL,
    "WorkspacePath" text NULL,
    "IamId" text NULL,
    CONSTRAINT "PK_Learners" PRIMARY KEY ("Id")
);


CREATE TABLE "LearningObjectFeedback" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Rating" integer NOT NULL,
    "LearnerId" integer NOT NULL,
    "LearningObjectId" integer NOT NULL,
    "TimeStamp" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_LearningObjectFeedback" PRIMARY KEY ("Id")
);


CREATE TABLE "QuestionSubmissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SubmittedAnswerIds" integer[] NULL,
    "QuestionId" integer NOT NULL,
    "LearnerId" integer NOT NULL,
    "IsCorrect" boolean NOT NULL,
    "TimeStamp" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_QuestionSubmissions" PRIMARY KEY ("Id")
);


CREATE TABLE "Units" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    CONSTRAINT "PK_Units" PRIMARY KEY ("Id")
);


CREATE TABLE "ArrangeTaskContainerSubmissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ContainerId" integer NOT NULL,
    "ElementIds" integer[] NULL,
    "ArrangeTaskSubmissionId" integer NULL,
    CONSTRAINT "PK_ArrangeTaskContainerSubmissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ArrangeTaskContainerSubmissions_ArrangeTaskSubmissions_Arra~" FOREIGN KEY ("ArrangeTaskSubmissionId") REFERENCES "ArrangeTaskSubmissions" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "ArrangeTasks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Text" text NULL,
    CONSTRAINT "PK_ArrangeTasks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ArrangeTasks_AssessmentEvents_Id" FOREIGN KEY ("Id") REFERENCES "AssessmentEvents" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Questions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Text" text NULL,
    CONSTRAINT "PK_Questions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Questions_AssessmentEvents_Id" FOREIGN KEY ("Id") REFERENCES "AssessmentEvents" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Challenges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Url" text NULL,
    "Description" text NULL,
    "TestSuiteLocation" text NULL,
    "SolutionIdForeignKey" integer NOT NULL,
    CONSTRAINT "PK_Challenges" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Challenges_AssessmentEvents_Id" FOREIGN KEY ("Id") REFERENCES "AssessmentEvents" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Challenges_InstructionalEvents_SolutionIdForeignKey" FOREIGN KEY ("SolutionIdForeignKey") REFERENCES "InstructionalEvents" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Images" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Url" text NULL,
    "Caption" text NULL,
    CONSTRAINT "PK_Images" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Images_InstructionalEvents_Id" FOREIGN KEY ("Id") REFERENCES "InstructionalEvents" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Texts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Content" text NULL,
    CONSTRAINT "PK_Texts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Texts_InstructionalEvents_Id" FOREIGN KEY ("Id") REFERENCES "InstructionalEvents" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Videos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Url" text NULL,
    CONSTRAINT "PK_Videos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Videos_InstructionalEvents_Id" FOREIGN KEY ("Id") REFERENCES "InstructionalEvents" ("Id") ON DELETE CASCADE
);


CREATE TABLE "KnowledgeComponents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Description" text NULL,
    "UnitId" integer NULL,
    CONSTRAINT "PK_KnowledgeComponents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_KnowledgeComponents_Units_UnitId" FOREIGN KEY ("UnitId") REFERENCES "Units" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "ArrangeTaskContainers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ArrangeTaskId" integer NOT NULL,
    "Title" text NULL,
    CONSTRAINT "PK_ArrangeTaskContainers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ArrangeTaskContainers_ArrangeTasks_ArrangeTaskId" FOREIGN KEY ("ArrangeTaskId") REFERENCES "ArrangeTasks" ("Id") ON DELETE CASCADE
);


CREATE TABLE "QuestionAnswers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "QuestionId" integer NOT NULL,
    "Text" text NULL,
    "IsCorrect" boolean NOT NULL,
    "Feedback" text NULL,
    CONSTRAINT "PK_QuestionAnswers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_QuestionAnswers_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ChallengeFulfillmentStrategies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodeSnippetId" text NULL,
    "ChallengeId" integer NULL,
    CONSTRAINT "PK_ChallengeFulfillmentStrategies" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChallengeFulfillmentStrategies_Challenges_ChallengeId" FOREIGN KEY ("ChallengeId") REFERENCES "Challenges" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "ArrangeTaskElements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ArrangeTaskContainerId" integer NOT NULL,
    "Text" text NULL,
    CONSTRAINT "PK_ArrangeTaskElements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ArrangeTaskElements_ArrangeTaskContainers_ArrangeTaskContai~" FOREIGN KEY ("ArrangeTaskContainerId") REFERENCES "ArrangeTaskContainers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "BasicMetricCheckers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "PK_BasicMetricCheckers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BasicMetricCheckers_ChallengeFulfillmentStrategies_Id" FOREIGN KEY ("Id") REFERENCES "ChallengeFulfillmentStrategies" ("Id") ON DELETE CASCADE
);


CREATE TABLE "BasicNameCheckers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BannedWords" text[] NULL,
    "RequiredWords" text[] NULL,
    "HintId" integer NULL,
    CONSTRAINT "PK_BasicNameCheckers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BasicNameCheckers_ChallengeFulfillmentStrategies_Id" FOREIGN KEY ("Id") REFERENCES "ChallengeFulfillmentStrategies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BasicNameCheckers_ChallengeHints_HintId" FOREIGN KEY ("HintId") REFERENCES "ChallengeHints" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "MetricRangeRules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MetricName" text NULL,
    "FromValue" double precision NOT NULL,
    "ToValue" double precision NOT NULL,
    "HintId" integer NULL,
    "MetricCheckerForeignKey" integer NULL,
    CONSTRAINT "PK_MetricRangeRules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MetricRangeRules_BasicMetricCheckers_MetricCheckerForeignKey" FOREIGN KEY ("MetricCheckerForeignKey") REFERENCES "BasicMetricCheckers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_MetricRangeRules_ChallengeHints_HintId" FOREIGN KEY ("HintId") REFERENCES "ChallengeHints" ("Id") ON DELETE RESTRICT
);


CREATE INDEX "IX_ArrangeTaskContainers_ArrangeTaskId" ON "ArrangeTaskContainers" ("ArrangeTaskId");


CREATE INDEX "IX_ArrangeTaskContainerSubmissions_ArrangeTaskSubmissionId" ON "ArrangeTaskContainerSubmissions" ("ArrangeTaskSubmissionId");


CREATE INDEX "IX_ArrangeTaskElements_ArrangeTaskContainerId" ON "ArrangeTaskElements" ("ArrangeTaskContainerId");


CREATE INDEX "IX_BasicNameCheckers_HintId" ON "BasicNameCheckers" ("HintId");


CREATE INDEX "IX_ChallengeFulfillmentStrategies_ChallengeId" ON "ChallengeFulfillmentStrategies" ("ChallengeId");


CREATE INDEX "IX_Challenges_SolutionIdForeignKey" ON "Challenges" ("SolutionIdForeignKey");


CREATE INDEX "IX_KnowledgeComponents_UnitId" ON "KnowledgeComponents" ("UnitId");


CREATE INDEX "IX_MetricRangeRules_HintId" ON "MetricRangeRules" ("HintId");


CREATE INDEX "IX_MetricRangeRules_MetricCheckerForeignKey" ON "MetricRangeRules" ("MetricCheckerForeignKey");


CREATE INDEX "IX_QuestionAnswers_QuestionId" ON "QuestionAnswers" ("QuestionId");


