<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="UseCases\Learning\Prompts\EvaluationFeedbackPrompt.md" />
    <EmbeddedResource Include="UseCases\Learning\Prompts\ScorePrompt.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Tutor.BuildingBlocks.AI.Core\Tutor.BuildingBlocks.AI.Core.csproj" />
    <ProjectReference Include="..\..\Courses\Tutor.Courses.API\Tutor.Courses.API.csproj" />
    <ProjectReference Include="..\Tutor.Elaborations.API\Tutor.Elaborations.API.csproj" />
  </ItemGroup>

</Project>
